config/routes.rb
PizzaChain::Application.routes.draw do
  resources :restaurants, only: [:index, :show]

  root :to => 'restaurants#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/pizza.rb
class Pizza < ActiveRecord::Base
  belongs_to :restaurant
  attr_accessible :name, :price, :description, :restaurant_id

  validates :name, :price, :description, :restaurant_id, presence: true
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_one :schedule
  has_many :pizzas
  attr_accessible :name, :pizzas_attributes, :schedule_attributes

  accepts_nested_attributes_for :pizzas, :schedule

  validates :name, uniqueness: true, presence: true

  def to_param
    [id, name.parameterize].join("-")
  end
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :restaurant
  attr_accessible(:title,
                  :body,
                  :open_weekday,
                  :open_weekend,
                  :close_weekday,
                  :close_weekend)

  after_initialize :defaults

  validates(:open_weekday,
            :open_weekend,
            :close_weekday,
            :close_weekend,
            format: { with: /\A\s*\d\d:\d\d\s*/, message: "Use the following format: hh:mm " })

  validate :check_if_time_values_are_correct

  def open_weekend
    open_saturday
  end

  def open_weekend=(time)
    self.open_saturday = time.strip
  end

  def close_weekend
    close_saturday
  end

  def close_weekend=(time)
    self.close_saturday = time.strip
  end

  def open_weekday
    open_monday
  end

  def open_weekday=(time)
    self.open_monday = time.strip
  end

  def close_weekday
    close_monday
  end

  def close_weekday=(time)
    self.close_monday = time.strip
  end

  private
  def defaults
    open = '08:00'
    close = '20:00'
    self.open_saturday ||= open
    self.open_monday ||= open
    self.close_saturday ||= close
    self.close_monday ||= close
  end

  def check_if_time_values_are_correct
    [:open_weekday, :open_weekend, :close_weekday, :close_weekend].each do |method|
      time = send(method)
      h, m = time.split(":")
      if h.to_i > 24 || m.to_i > 59
        errors.add(method, "The time is incorrect")
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find params[:id]
    @schedule = @restaurant.schedule
    @pizzas = @restaurant.pizzas
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PizzaChain</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/index.html.erb
<div class="small">
  <%= link_to "login to admin page", admin_root_path %>
</div>

<h1>Pizzas Chain</h1>

<h2>List of pizzerias:</h2>
<ul>
  <% @restaurants.each do |restaurant| -%>
    <li>
      <%= restaurant.name %>
      <%= link_to "see offer", restaurant_path(restaurant) %></li>
  <% end -%>
</ul>

app/views/restaurants/show.html.erb
<h1>Restaurant <%= @restaurant.name %></h1>
<div>
  <h3>Openning hours:</h3>
  <p>Weekday: <%= @schedule.open_weekday %> : <%= @schedule.close_weekday %></p>
  <p>Weekend: <%= @schedule.open_weekend %> : <%= @schedule.close_weekend %></p>
</div>
<div>
  <h3>Offer:</h3>
  <table>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
    </tr>
    <% @pizzas.each do |pizza| -%>
      <tr>
        <td><%= pizza.name %></td>
        <td><%= pizza.price %></td>
        <td><%= pizza.description %></td>
      </tr>
    <% end -%>
  </table>
</div>
<p>
  <%= link_to "Back to restaurants", root_path %>
</p>